key_filename: KEY.key
password_filename: passwords.db
log_directory: ./logs
data_directory: ./data
appearance: System
theme: dark-blue
geometry: 856x482
verbose: true
black_image: ./ui/assets/black.png
white_image: ./ui/assets/white.png