name: Build

on:
  workflow_call:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '>=1.26'
          cache: true

      - name: Make Dist Folder
        run: |
          mkdir dist

      - name: Install Linux Dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc libgl1-mesa-dev xorg-dev

      - name: Install Fyne CLI
        run: |
          go install fyne.io/tools/cmd/fyne@latest

      - name: Package with Fyne On Windows
        if: runner.os == 'Windows'
        env:
          CGO_ENABLED: 1
        run: |
          fyne package -os windows -release -id "com.github.parol" -name "Parol" -src ${{ github.workspace }}\cmd -icon "${{ github.workspace }}\ui\assets\black_logo.png" -cert windows

      - name: Package with Fyne On Darwin (Apple Silicon)
        if: runner.os == 'macOS'
        run: |
          GOARCH=arm64 fyne package -os darwin -release -id "com.github.parol" -name "Parol-arm64" -src ${{ github.workspace }}/cmd -icon "${{ github.workspace }}/ui/assets/black_logo.png"

      - name: Package with Fyne On Darwin (Intel Silicon)
        if: runner.os == 'macOS'
        run: |
          GOARCH=amd64 fyne package -os darwin -release -id "com.github.parol" -name "Parol-amd64" -src ${{ github.workspace }}/cmd -icon "${{ github.workspace }}/ui/assets/black_logo.png"
          mv *.app dist
      
      - name: Package with Fyne On Linux
        if: runner.os == 'Linux'
        run: |
          fyne package -os linux -release -id "com.github.parol" -name "Parol" -src ${{ github.workspace }}/cmd -icon "${{ github.workspace }}/ui/assets/black_logo.png"
          mv *.xz dist

      - name: Sign Executable
        if: runner.os == 'Windows'
        uses: skymatic/code-sign-action@v1
        env:
          WINDOWS_CERT_BASE64: ${{ secrets.WINDOWS_CERT_BASE64 }}
        with:
          certificate: $WINDOWS_CERT_BASE64
          password: ${{ secrets.WINDOWS_CERTIFICATE_PASSWORD }}
          certificatesha1: ${{ secrets.WINDOWS_CERT_SHA1 }}
          # certificatename: ${{ secrets.GITHUB_TOKEN }}
          folder: '.'
          recursive: false
          description: 'Password Manager.'
          timestampUrl: 'http://timestamp.digicert.com'

      - name: Move Artifact
        if: runner.os == 'Windows'
        env:
          WINDOWS_CERT_BASE64: 'MIIKSQIBAzCCCgUGCSqGSIb3DQEHAaCCCfYEggnyMIIJ7jCCBg8GCSqGSIb3DQEHAaCCBgAEggX8MIIF+DCCBfQGCyqGSIb3DQEMCgECoIIE/jCCBPowHAYKKoZIhvcNAQwBAzAOBAiFg2JTRz6JkwICB9AEggTY0tf64HwRE7mU7m2cYVRUjloGxqBvstYHicUt1cLChmk8dG+rU9Zw5Tq6WMmsQxbvZtRLhy5A3YnhhJkLDpUTe+XFFKleOexrqeXf5p1pkBjXGNjeq/uNwLIX0q64qqe5j67U6R5501+TOeRDKG+ZPrGspkmo85SATJ/hcW9rbGdHlbLSdDGfW/YMakAXrgUpWjOUtww8Vmhv/KU2Vc/j5XP/nvwkyLzJWHdRMiQpIk0tIUx8DOmqeOt6iJSVWE/7QEUfpk5D2VXbxjtCz0iwHLB+MBftj0J2q4ooxmCQhlQvTeTWAommQDhuf0h/1BCmiWT02Sp/eNamqqOylavOQuL2RDJLDN+MRlc4H3a1MyAkujxecWTFx4aCYim9KuCg7uzMeRbKSPgahE/3g20M31BiDX/qhokrY/oNMgQ3WaIGtcUC1gnF32hKZmYyKdopfFbaqdtCn2uKiZRoMf/CEQMYxfww4mt0WhEakrbTjFpM7r+H0UulWOT6s4UPHJ/Iilm/NbNoCgkXxeg15vz6FFrKF0pr8ZSvSWWxXa6db9iMiKJKfXSy7u+oTNwg0JnFyL23WtzLbJ7WtzZyVcBDVCtg13uD6+9XFgcQBNtYhVVR3qj8KZPpcDg/IH7Jg1AOt5ADkuVRMofL/ctVHP0tyXPwxWYbvcYvTk+TzxlCE0JpwvAPmp/2cTwxpuNFExp2P8y/AtodPXNgm1+Mf+8R0hO2brs8fi0XQJion7z/9lJd25bZ+uApyn1PpsV0gc29IHAcLAbvk1yc6Fn3XgytReVnSPtJdD/TUBDZl3rEgtBNTA1rnYrkKyD7IJ4YspE+7k0hj6WqzBhQ59Eq/+Ca6DiuzGRMPYgj8vVoEBeHLkJOOjI0LZbbbHhQKtrx4Y1Wr0MiE5ZWjhqi/O07gOzaaCfPy/lq4uxR+NERZf6Qdq3Qk0219Z+rNU0SvJeFRMdw2TF/FkJS0BlxhERdVAykjzPO+sapKNGzBkYnHTR50Hm68Xapy7VUKWBe53MijiBQa3YcuiD+66EWZTJLTTP2cYQrLwaa4b6UndtxoF2KBfCqimoIYpEbl0pGVD5MAz6wOWlMZWMwVN6izgY3OQJ269JhxEyf5rUVt17VUyS2uDCD4HPpfxxS8mFmI5TphGuKB4XG1xtNUt9Pj7zE1KjGozCTfsw7MOKEmnHfZl5he5RU0i77jbQgOt8yrgn7oRCoPepRnrTWIiKq2iYb+e/T6KBQuFL3KFnCz7yb0DbGJ4Ul73qhn7VxlQ5ad1HpTAMnJy82dkZEamKSueaLZXpMXVCBImY9Z3lfcIUdm0UdR85cvXqqI2jQAc5nqehuk7xCy+pmN4+tbP5UDalLiYHoyqtfEVQwxWdcTuAQVWceuQy47+orONjNR1Puj68ALjNbh29KbFXuiYGeYhq+JfVaM+siXagGQsWOBvegDO6f+nzEzSKkFMOvEoxi/UJY+KwylcunXTjUUgNPiax2+rvut2hdINx9Ql3+NPm2UNYJoJg39xAPomkcLsWF5AQ+MU/qEAmXPle7nEZK0vfEi2Nlrxfr3aDs8rquqhFCdLWvHA/OyW0TAnLkqfEdn4aI+pybb/mcoDTxeTiMuy5BRwu9zWd5mtqIuyOZynvwrKpbK67vwngBUVWdODGB4jANBgkrBgEEAYI3EQIxADATBgkqhkiG9w0BCRUxBgQEAQAAADBdBgkqhkiG9w0BCRQxUB5OAHQAZQAtAGQAMAA3ADUAYQAxADMAMgAtADkAMgA4ADUALQA0AGEANgAzAC0AOQA1ADcAZAAtAGUAZgA0ADgAMAAzADEANgA5ADgAOABjMF0GCSsGAQQBgjcRATFQHk4ATQBpAGMAcgBvAHMAbwBmAHQAIABTAG8AZgB0AHcAYQByAGUAIABLAGUAeQAgAFMAdABvAHIAYQBnAGUAIABQAHIAbwB2AGkAZABlAHIwggPXBgkqhkiG9w0BBwagggPIMIIDxAIBADCCA70GCSqGSIb3DQEHATAcBgoqhkiG9w0BDAEDMA4ECBabQWYhGCEDAgIH0ICCA5AdeVUg7ch8M1raOW8mmFiYDNBZqxIslcb3HvHMW7E+7h5GiZPRYz+qtokQ9dBwzT+eb4U819Ubij7qOKGuGqs4VFAsZVUo6CXAf0QScsdAEWpSSUsPfFOOhfYWCt/TBHyyhS4omcfazlPpneaaL1TKWKZKdpbYjTRFVusnRxO7lhJyyFJMLGco+PUW3mPKTjfRUA7vKRYan3Fa7sofElupzdCe6ZSFWtPhod87SgLpzf3Jia3u4mv63J9pnQzHZ9GUzH8tXnEHnVRMYP6KICzgnhY2cOepT/yLS2NNxtE8TG8U+KZRC+qIssmyX4v2rzR9fMMf/qPAxpNGOkZ2icZljz9bhIBlxH/EQODE0uMO1irsvPCON9340qyYvK2VTevh8e3bUW4NO0X++Ut3wp2BLC2atU89hk/CxasZSyAZoVkY07FtS8sJjeWcJ5DgeSgPZusxl22hGP3+DWCYQD4+S6dkfz63cJPXdEWnO2GYf4iq8ZvyoVLkVZJxdLE36L1hXBA/+bRPvKLkmXNfDZv1j6KwFM4D2Q5E/xhMnaIaR6KCXW8njPnViIvPapdxouLz7K9ICbwqcR57WxVroABPxAzxr1VhKZFTmsYjJz7RT9ICZ80xstMvcQbYZsEKRc69MMKRU6qmV5mQeWkR2JRtro+fTPA8PLJQQ09+E/r1t7ftY3cfRlGGuv0VU5NNvelBq4vTIV7DON+PFOEXdvLNYEEbwxI3eysigld93KGZsV0NEml2k75fgaWCdlSh5armQs9TDgQxTu2p2pgZI1iTEY/P10NUxS1+NnWtEqexyyj9nwQeaa1RNSj5lq8PfSK26SUJvfMeApHZH4IPPpbGFPqR0lt7epmb+KnEM8Vu9uvhKzyoau6ORf4YCTR88zpV5C5BJVGS6pa+WknOEBcSlC13NXGVatX4wcuTB5eXdIkhcfjxPloijnTv1/BBHpgMcoDeowH2V1ng/qbEPNILOLa8rviEmGo+CXNz0vR6rODTh5xtNX6t27r2FiNGWHZsMBP2iFAParBiNqRv+zQDmB2ZndOPqfnsuOvlocMlYU5Kb1eEzEmPSlyDcA00doFT0rMJo7Tok6NrV/JSG2/2WKeRPwPpdzh8lGMILoECRaU3pkB1LkJwQPxr+VcQGn24MWQUlj5WizcuRu7akzwH/ZNHuDCBQjDOKWjvFnhtx90I5sJGxpt+TzM1hMqMm18wOzAfMAcGBSsOAwIaBBRySx41UdiZmd6hmdwaWB/dpn6DiQQUZEOlKRRVOUAbaJF4JJoCmhTPFukCAgfQ'
        run: |
          Move-Item -Path "*/Parol.exe" -Destination dist -Force
          echo $WINDOWS_CERT_BASE64
          echo "${{ secrets.WINDOWS_CERTIFICATE_PASSWORD }}"


      - name: Upload Individual Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Parol-${{ matrix.os }}
          path: ${{ github.workspace }}/dist/*